SELECT
    B.ADMINIST_ZONE_NM AS CITY_NAME,
    A.AGRDE_SE_CD,
    A.POPLTN_CNT
FROM
(
    SELECT
        A.AGRDE_SE_CD,
        MAX(A.POPLTN_CNT) AS POPLTN_CNT
        
    FROM TB_POPLTN A
    WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
    AND A.POPLTN_SE_CD IN 'T'
    GROUP BY AGRDE_SE_CD
    ORDER BY AGRDE_SE_CD
) A, TB_POPLTN B
WHERE B.POPLTN_CNT = A.POPLTN_CNT
ORDER BY A.AGRDE_SE_CD;